# Generated by Django 4.0.5 on 2022-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
